# https://docs.github.com/en/actions

on:
  push:
    tags:
      - "**"
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to Release'
        required: true

name: Release

jobs:
  release:
    name: Release

    env:
      RELEASE_TAG: ${{ inputs.tag || github.ref_name }}

    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          coverage: none
          extensions: none
          tools: none

      - name: Parse ChangeLog
        run: build/scripts/extract-release-notes.php ${{ env.RELEASE_TAG }} > release-notes.md

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.RELEASE_TAG }}
          name: PHPUnit ${{ env.RELEASE_TAG }}
          bodyFile: release-notes.md
          commit: "12.4"

      - name: Announce release
        id: mastodon
        uses: cbrgm/mastodon-github-action@v2
        with:
          access-token: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          url: ${{ secrets.MASTODON_URL }}
          language: "en"
          message: "#PHPUnit ${{ env.RELEASE_TAG }} has been released: https://github.com/sebastianbergmann/phpunit/releases/tag/${{ env.RELEASE_TAG }}"
